In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [2]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [5]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:
df.isna()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [8]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
x

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train

array([[6.40e+01, 6.10e+00, 2.90e+00, 4.70e+00, 1.40e+00],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [2.70e+01, 5.00e+00, 3.40e+00, 1.60e+00, 4.00e-01],
       [1.04e+02, 6.30e+00, 2.90e+00, 5.60e+00, 1.80e+00],
       [1.30e+02, 7.20e+00, 3.00e+00, 5.80e+00, 1.60e+00],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.42e+02, 6.90e+00, 3.10e+00, 5.10e+00, 2.30e+00],
       [1.16e+02, 6.40e+00, 3.20e+00, 5.30e+00, 2.30e+00],
       [7.40e+01, 6.10e+00, 2.80e+00, 4.70e+00, 1.20e+00],
       [1.29e+02, 6.40e+00, 2.80e+00, 5.60e+00, 2.10e+00],
       [1.07e+02, 4.90e+00, 2.50e+00, 4.50e+00, 1.70e+00],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [8.40e+01, 6.00e+00, 2.70e+00, 5.10e+00, 1.60e+00],
       [1.43e+02, 5.80e+00, 2.70e+00, 5.10e+00, 1.90e+00],
       [4.80e+01, 4.60e+00, 3.20e+00, 1.40e+00, 2.00e-01],
       [9.10e+01, 5.50e+00, 2.60e+00, 4.40e+00, 1.20e+00],
       [1.47e+02, 6.30e+00, 2.50e+00, 5.00e+00, 1.90e+00

In [12]:
x_test

array([[1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.06e+02, 7.60e+00, 3.00e+00, 6.60e+00, 2.10e+00],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [2.10e+01, 5.40e+00, 3.40e+00, 1.70e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [8.20e+01, 5.50e+00, 2.40e+00, 3.70e+00, 1.00e+00],
       [1.80e+01, 5.10e+00, 3.50e+00, 1.40e+00, 3.00e-01],
       [9.50e+01, 5.60e+00, 2.70e+00, 4.20e+00, 1.30e+00],
       [9.40e+01, 5.00e+00, 2.30e+00, 3.30e+00, 1.00e+00],
       [1.38e+02, 6.40e+00, 3.10e+00, 5.50e+00, 1.80e+00],
       [7.00e+01, 5.60e+00, 2.50e+00, 3.90e+00, 1.10e+00],
       [2.90e+01, 5.20e+00, 3.40e+00, 1.40e+00, 2.00e-01],
       [1.24e+02, 6.30e+00, 2.70e+00, 4.90e+00, 1.80e+00],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [1.41e+02, 6.70e+00, 3.10e+00, 5.60e+00, 2.40e+00],
       [8.70e+01, 6.70e+00, 3.10e+00, 4.70e+00, 1.50e+00],
       [5.20e+01, 6.40e+00, 3.20e+00, 4.50e+00, 1.50e+00

In [13]:
y_train

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
x_test

array([[-1.46337564, -0.5814583 ,  1.31166325, -1.23649206, -1.23236565],
       [ 0.64228941,  2.32583322, -0.23580463,  1.60694408,  1.07326374],
       [-1.48554054, -1.24220638, -0.01473779, -1.23649206, -1.35371456],
       [-1.24172669, -0.5814583 ,  0.64846273, -1.12498476, -1.23236565],
       [-1.41904585, -1.37435599, -0.23580463, -1.29224571, -1.35371456],
       [ 0.11033192, -0.44930869, -1.56220566, -0.00991176, -0.26157433],
       [-1.30822138, -0.97790715,  0.86952957, -1.29224571, -1.11101673],
       [ 0.39847556, -0.31715908, -0.89900515,  0.26885649,  0.10247242],
       [ 0.37631067, -1.11005676, -1.7832725 , -0.23292636, -0.26157433],
       [ 1.35156606,  0.74003784, -0.01473779,  0.99365394,  0.70921699],
       [-0.15564682, -0.31715908, -1.34113882,  0.10159554, -0.14022541],
       [-1.06440753, -0.84575753,  0.64846273, -1.29224571, -1.23236565],
       [ 1.04125753,  0.60788823, -0.89900515,  0.65913204,  0.70921699],
       [-1.59636502, -1.11005676,  1.0

In [16]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor'],
      dtype='<U15')

In [ ]:
from sklearn.metrics i,accuracy_score import
classification_report,confusion_matrix,accuracy_score,confusionmatrixD


